Metrics/LineLength:
  Max: 300
  #80

Metrics/BlockLength:
  Max: 300
  #100

Metrics/MethodLength:
  Max: 20
  #10

Metrics/AbcSize:
  Max: 30
  #15

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MixinUsage:
  Enabled: false


